### ISSUE TITLE
3. Ny dialog

### ISSUE THREAD

**Issue by AbbeVass** [AbbeVass/GdxGame#2]
Lägg till en ny dialog i spelet. Gör så att `TOWN_FOLK5` har den nya dialogen.
(`TOWN_FOLK5` kanske inte finns än. Om den som har uppgift 7 inte har lagt till den än, kanske du måste vänta, eller testa att ge dialogen till en annan NPC och sen återställa och ge till `TOWN_FOLK5` när uppgift 7 är färdig.)

Dialog:
> "Did you hear about the Great Chicken Chase of Eldertown?"
> "No? Well, I don't really have time to tell the story, anyway."
> "See you around, adventurer."

**Comment by tedgryttman** [comment]
Jag gjorde det nu
